name: ci-wf
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Weclome Step
        run: echo "starting the linting job on the runner"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install HTMLHint and Stylelint
        run: |
          npm install htmlhint --save-dev
          npm install stylelint --save-dev
      - name: Lint HTML & CSS
        run: npx htmlhint "**/*.html"
      - name: Lint CSS
        run: npx stylelint "**/*.css"
  build-job:
    needs: lint-job
    runs-on: ubuntu-latest
    steps:
      - name: Weclome Message In Build-Job
        run: echo "Allah Always Help Me"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Parcel
        run: npm install parcel --save-dev
      - name: Build Website With Parcel
        run: npx parcel ./src/index.html --dist-dir staging
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: build-artifact-ia
          path: ./staging